OnlineStoreDemo/OnlineStore.Web/Models/APIResponse.cs
namespace OnlineStore.Web.Models;
public class APIResponse
{
    public string Data { get; set; }
    public bool IsSuccess { get; set; }
    public string Message { get; set; }
}

public class APIResponse<T>
{
    public string Message { get; set; }
    public T Data { get; set; }
    public bool IsSuccess { get; set; }
}

OnlineStoreDemo/OnlineStore.Web/Models/ErrorViewModel.cs
namespace OnlineStore.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OnlineStoreDemo/OnlineStore.Web/Models/LoginModel.cs
namespace OnlineStore.Web.Models;
public class LoginModel
{
    public string Username { get; set; }
    public string Password { get; set; }
}

OnlineStoreDemo/OnlineStore.Web/Models/OrderItemModel.cs
namespace OnlineStore.Web.Models;

public class OrderItemModel
{
    public int Id { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    public int OrderId { get; set; }
    public int ProductId { get; set; }
    public ProductModel? Product { get; set; }
}

OnlineStoreDemo/OnlineStore.Web/Models/OrderModel.cs
namespace OnlineStore.Web.Models;

public class OrderModel
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public decimal TotalPrice { get; set; }
    public string Status { get; set; }
    public DateTime CreatedAt { get; set; }
    public List<OrderItemModel> OrderItems { get; set; }
}


public enum OrderStatus
{
    Pending,
    Completed
}

OnlineStoreDemo/OnlineStore.Web/Models/ProductModel.cs
namespace OnlineStore.Web.Models;

public class ProductModel
{
    public int Id { get; set; }
    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int Stock { get; set; }
    public DateTime CreatedAt { get; set; }
    public int? UserId { get; set;}
}

OnlineStoreDemo/OnlineStore.Web/Models/RegisterModel.cs
namespace OnlineStore.Web.Models;
public class RegisterModel
{
    public string Username { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
}

OnlineStoreDemo/OnlineStore.Web/Models/UserModel.cs
namespace OnlineStore.Web.Models;
public class UserModel
{
    public int Id { get; set; }
    public string Username { get; set; }
    public string Email { get; set; }
    public bool IsAdmin { get; set; }
    public string Token { get; set; }
    public string TokenExpiryTime { get; set; }
}

OnlineStoreDemo/OnlineStore.Web/Controllers/CartController.cs
using OnlineStore.Web.Helper;
using Microsoft.AspNetCore.Mvc;

namespace OnlineStore.Web.Controllers;

[Session]
public class CartController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

OnlineStoreDemo/OnlineStore.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Web.Helper;
using OnlineStore.Web.Models;

namespace OnlineStore.Web.Controllers;

[Session]
public class OrderController : Controller
{
    private readonly IApiHelper _apiHelper;
    public OrderController(IApiHelper apiHelper)
    {
        _apiHelper = apiHelper;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public async Task<APIResponse<List<OrderModel>>> GetOrders()
    {
        var userId = HttpContext.Session.GetInt32("_SessionUserId");
        var responseMessage = await _apiHelper.MakeApiCallAsync("orders?userId=" + userId, HttpMethod.Get, HttpContext, null);
        var responseAsync = await BaseMethod.DeserializeApiResponseAsync<List<OrderModel>>(responseMessage);
        return responseAsync;
    }

    [HttpPost]
    public async Task<APIResponse<List<OrderItemModel>>> GetOrderDetails([FromBody] OrderModel model)
    {
        var responseMessage = await _apiHelper.MakeApiCallAsync("orders/" + model.Id, HttpMethod.Get, HttpContext, null);
        var responseAsync = await BaseMethod.DeserializeApiResponseAsync<List<OrderItemModel>>(responseMessage);
        return responseAsync;
    }

    [HttpPost]
    public async Task<APIResponse<string>> CreateOrder([FromBody] OrderModel model)
    {
        model.Status = Enum.GetName(OrderStatus.Pending);
        model.UserId = HttpContext.Session.GetInt32("_SessionUserId").Value;
        var responseMessage = await _apiHelper.MakeApiCallAsync("orders", HttpMethod.Post, HttpContext, model);
        var responseAsync = await BaseMethod.DeserializeApiResponseAsync<string>(responseMessage);
        return responseAsync;
    }
}

OnlineStoreDemo/OnlineStore.Web/Controllers/ProductController.cs
using OnlineStore.Web.Helper;
using OnlineStore.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace OnlineStore.Web.Controllers;

[Session]
public class ProductController : Controller
{
    private readonly IApiHelper _apiHelper;
    public ProductController(IApiHelper apiHelper)
    {
        _apiHelper = apiHelper;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public async Task<APIResponse<List<ProductModel>>> GetProducts()
    {
        var responseMessage = await _apiHelper.MakeApiCallAsync("products", HttpMethod.Get, HttpContext, null);
        var responseAsync = await BaseMethod.DeserializeApiResponseAsync<List<ProductModel>>(responseMessage);
        return responseAsync;
    }

    [HttpPost]
    public async Task<APIResponse<string>> CreateProduct([FromBody] ProductModel model)
    {
        model.UserId = HttpContext.Session.GetInt32("_SessionUserId");
        var responseMessage = await _apiHelper.MakeApiCallAsync("products", HttpMethod.Post, HttpContext, model);
        var responseAsync = await BaseMethod.DeserializeApiResponseAsync<string>(responseMessage);
        return responseAsync;
    }

    [HttpPost]
    public async Task<APIResponse<string>> EditProduct([FromBody] ProductModel model)
    {
        model.UserId = HttpContext.Session.GetInt32("_SessionUserId");
        var responseMessage = await _apiHelper.MakeApiCallAsync("products/"+ model.Id, HttpMethod.Put, HttpContext, model);
        var responseAsync = await BaseMethod.DeserializeApiResponseAsync<string>(responseMessage);
        return responseAsync;
    }

    [HttpPost]
    public async Task<APIResponse<string>> DeleteProduct([FromBody] ProductModel model)
    {
        model.UserId = HttpContext.Session.GetInt32("_SessionUserId");
        var responseMessage = await _apiHelper.MakeApiCallAsync("products/"+ model.Id + "?userId="+ model.UserId, HttpMethod.Delete, HttpContext, null);
        var responseAsync = await BaseMethod.DeserializeApiResponseAsync<string>(responseMessage);
        return responseAsync;
    }
}

OnlineStoreDemo/OnlineStore.Web/Controllers/UserController.cs
using OnlineStore.Web.Helper;
using OnlineStore.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace OnlineStore.Web.Controllers;
public class UserController : Controller
{
    private readonly IApiHelper _apiHelper;
    public UserController(IApiHelper apiHelper)
    {
        _apiHelper = apiHelper;
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<APIResponse<UserModel>> SignIn([FromBody] LoginModel model)
    {
        var responseMessage = await _apiHelper.MakeApiCallAsync("User/Login", HttpMethod.Post, model);
        var responseAsync = await BaseMethod.DeserializeApiResponseAsync<UserModel>(responseMessage);
        if (responseAsync.IsSuccess)
        {
            HttpContext.Session.SetString("_SessionToken", responseAsync.Data.Token);
            HttpContext.Session.SetString("_SessionUsername", responseAsync.Data.Username);
            HttpContext.Session.SetInt32("_SessionUserId", responseAsync.Data.Id);
            HttpContext.Session.SetInt32("_SessionIsAdmin", responseAsync.Data.IsAdmin ? 1 : 0);
        }
        return responseAsync;
    }

    [HttpPost]
    public async Task<APIResponse<string>> SignUp([FromBody] RegisterModel model)
    {
        var responseMessage = await _apiHelper.MakeApiCallAsync("User/Register", HttpMethod.Post, model);
        var responseAsync = await BaseMethod.DeserializeApiResponseAsync<string>(responseMessage);
        return responseAsync;
    }

    [HttpGet]
    public async Task<string> Logout()
    {

        HttpContext.Session.Remove("_SessionToken");
        HttpContext.Session.Remove("_SessionUsername");
        HttpContext.Session.Remove("_SessionIsAdmin");
        HttpContext.Session.Remove("_SessionUserId");
        HttpContext.Session.Clear();
        var expiredCookie = new CookieOptions
        {
            Expires = DateTime.Now.AddDays(-1),
            IsEssential = true,
            HttpOnly = true,
        };
        Response.Cookies.Append("_OnlineStoreCookie", "", expiredCookie);

        return "Logout succcessfully.";
    }
}

OnlineStoreDemo/OnlineStore.Web/Views/Cart/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid pt-4 default-dashboard">
    <div class="row">
        <div class="col-xxl-12">
            <div class="card">
                <div class="card-header card-no-border pb-0">
                    <div class="header-top">
                        <h4>Shopping Cart</h4>
                    </div>
                </div>
                <div class="card-body escrow">
                    <div class="table-responsive custom-scrollbar p-2">
                        <table class="display" id="cart-table" style="width: 100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Product</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total Price</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                        <div class="d-flex flex-column flex-md-row justify-content-between align-items-center mt-4 shadow rounded p-3 bg-white">
                            <h5 class="mb-3 mb-md-0">Total</h5>
                            <h5 id="total-price" class="mb-3 mb-md-0">$0.00</h5>
                            <button onclick="PlaceOrder()" class="btn btn-success">Place Order</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/js/ShoppingCartJs.js"></script>

OnlineStoreDemo/OnlineStore.Web/Views/Order/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid pt-4 default-dashboard">
    <div class="row">
        <div class="col-xxl-12">
            <div class="card">
                <div class="card-header card-no-border pb-0">
                    <div class="header-top">
                        <h4>Order History</h4>
                    </div>
                </div>
                <div class="card-body escrow">
                    <div class="table-responsive custom-scrollbar p-2">
                        <table class="display" id="orderTable" style="width: 100%">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Total Price</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="orderDetailsModal" tabindex="-1" aria-labelledby="orderDetailsModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="max-width:850px !important;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orderModalLabel">View Order Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Order Number</h3>
                        <p id="orderId"></p>
                    </div>
                    <div class="col-md-6">
                        <h3>Order Date</h3>
                        <p id="orderDate"></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <h3>User Name</h3>
                        <p id="userName">@Context.Session.GetString("_SessionUsername")</p>
                    </div>
                </div>
                <h2 class="h4">Order Items</h2>
                <div class="table-responsive custom-scrollbar p-2">
                    <table class="display" id="orderItemsTable" style="width: 100%">
                        <thead>
                            <tr>
                                <th>Product Name</th>
                                <th>Quantity</th>
                                <th>Price</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-md-12 d-flex justify-content-end">
                        <h2 class="h4">Grand Total: <span id="grandTotal"></span></h2>
                    </div>
                </div>
                <hr />
                <p class="text-center mb-0">Thank you for your order!</p>
            </div>
        </div>
    </div>
</div>


<script src="~/js/OrderJs.js"></script>

OnlineStoreDemo/OnlineStore.Web/Views/Shared/_Layout.cshtml
@{
    string userName = Context.Session.GetString("_SessionUsername");
    bool isAdmin = Context.Session.GetInt32("_SessionIsAdmin") == 1 ? true : false;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <link rel="icon" href="~/assets/images/favicon.png" type="image/x-icon" />
    <link rel="shortcut icon" href="~/assets/images/favicon.png" type="image/x-icon" />
    <title>Online Store</title>
    <!-- Google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,100;9..40,200;9..40,300;9..40,400;9..40,500;9..40,600;9..40,700;9..40,800;9..40,900;9..40,1000&display=swap|Material+Icons"
          rel="stylesheet" />
    <!-- Material-icon-font-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
          rel="stylesheet" />
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/scrollbar.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/responsive.bootstrap5.min.css" />
    <!-- Plugins css Ends-->
    <!-- latest jquery-->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap.css" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css" />
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.min.css" />
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/responsive.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet" />
    <style>
        .menu-dropdown {
            width: 160px !important;
            top: 16px !important;
            left: -12px !important;
            padding: 0 10px !important;
            visibility: visible !important;
            opacity: 1 !important;
            top: 55px !important;
            position: absolute !important;
            z-index: 8 !important;
            background-color: #fff !important;
            -webkit-transition: all linear 0.3s !important;
            transition: all linear 0.3s !important;
            -webkit-transform: translateY(0px) !important;
            transform: translateY(0px) !important;
            border-radius: 5px !important;
        }

        .modal-title{
            color:white !important;
        }
    </style>
</head>
<body>
    <!-- loader starts-->
    <div class="loader-wrapper">
        <div class="theme-loader">
            <div class="loader-p"></div>
        </div>
    </div>
    <!-- loader ends-->
    <!-- tap on top starts-->
    <div class="tap-top"><i data-feather="chevrons-up"></i></div>
    <!-- tap on tap ends-->
    <!-- page-wrapper Start-->
    <div class="page-wrapper compact-wrapper" id="pageWrapper">
        <!-- Page Header Start-->
        <div class="page-header">
            <div class="header-wrapper row m-0">
                <div class="header-logo-wrapper col-auto p-0">
                    <div class="logo-wrapper">
                        <a asp-action="Index" asp-controller="Product">
                            <img class="img-fluid for-light" src="~/assets/images/logo.svg" alt="" /><img class="img-fluid for-dark"
                                                                                                          src="~/assets/images/logo.svg"
                                                                                                          alt="" />
                        </a>
                    </div>
                    <div class="toggle-sidebar">
                        <span class="material-symbols-outlined">menu_open</span>
                    </div>
                </div>

                <div class="nav-right col-xxl-7 col-xl-6 col-auto box-col-6 pull-right right-header p-0 ms-auto">
                    <ul class="nav-menus me-3">

                        <li class="profile-nav" id="profileNav">
                            <div class="d-flex align-items-center">
                                <div class="flex-grow-1">
                                    <span>@userName</span>
                                    <i class="material-symbols-outlined" id="navArrowIcon">keyboard_arrow_down</i>
                                </div>
                            </div>
                            <ul class="profile-dropdown menu-dropdown shadow d-none">
                                <li>
                                    <a href="#" onclick="Logout()"><i class="material-symbols-outlined"> logout </i><span>Logout</span></a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- Page Header Ends-->
        <!-- Page Body Start-->
        <div class="page-body-wrapper">
            <!-- Page Sidebar Start-->
            <div class="sidebar-wrapper" data-layout="fill-svg">
                <div>
                    <div class="logo-wrapper">
                        <a asp-action="Index" asp-controller="Product"><img class="img-fluid" src="~/assets/images/logo.svg" alt="" /></a>
                        <div class="toggle-sidebar">
                            <div class="sidebar-toggle">
                                <span class="material-symbols-outlined">menu_open</span>
                            </div>
                        </div>
                    </div>
                    <div class="logo-icon-wrapper">
                        <a asp-action="Index" asp-controller="Product"><img class="img-fluid" src="~/assets/images/logo-icon.svg" alt="" /></a>
                    </div>
                    <nav class="sidebar-main">
                        <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
                        <div id="sidebar-menu">
                            <ul class="sidebar-links" id="simple-bar">
                                <li class="back-btn">
                                    <a href=""><img class="img-fluid" src="~/assets/images/logo-icon.svg" alt="" /></a>
                                    <div class="mobile-back text-end">
                                        <span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i>
                                    </div>
                                </li>
                                <li class="sidebar-list">
                                    <a class="sidebar-link sidebar-title link-nav" asp-action="Index" asp-controller="Product">
                                        <div class="fill-icon">
                                            <use class="material-symbols-outlined">dashboard</use>
                                        </div>
                                        <span>Products</span>
                                    </a>
                                </li>
                                @if (!isAdmin)
                                {
                                    <li class="sidebar-list">
                                        <a class="sidebar-link sidebar-title link-nav" asp-action="Index" asp-controller="Cart">
                                            <div class="fill-icon">
                                                <use class="material-symbols-outlined">shopping_cart</use>
                                            </div>
                                            <span>Shopping Cart</span>
                                        </a>
                                    </li>

                                    <li class="sidebar-list">
                                        <a class="sidebar-link sidebar-title link-nav" asp-action="Index" asp-controller="Order">
                                            <div class="fill-icon">
                                                <use class="material-symbols-outlined">swap_horiz</use>
                                            </div>
                                            <span>Order History</span>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                        <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
                    </nav>
                </div>
            </div>
            <!-- Page Sidebar Ends-->
            <div class="page-body">
                @RenderBody()
            </div>
        </div>

        <!-- Bootstrap js-->
        <script src="~/assets/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.min.js"></script>
        <!-- scrollbar js-->
        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>

        <script src="~/assets/js/simplebar.js"></script>
        <script src="~/assets/js/custom.js"></script>
        <!-- Sidebar jquery-->
        <!-- Plugins JS start-->
        <script src="~/assets/js/height-equal.js"></script>
        <script src="~/assets/js/tooltip-init.js"></script>
        <script src="~/assets/js/jquery.dataTables.min.js"></script>
        <script src="~/assets/js/jquery-ui.min.js"></script>
        <script src="~/assets/js/dataTables.bootstrap5.min.js"></script>
        <script src="~/assets/js/dataTables.responsive.min.js"></script>
        <script src="~/assets/js/responsive.bootstrap5.min.js"></script>
        <script src="~/assets/js/datatable.custom.js"></script>
        <script src="~/assets/js/sidebar-menu.js"></script>

        <script src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>

        <!-- Plugins JS Ends-->
        <!-- Theme js-->
        <script src="~/assets/js/script.js"></script>
        <!-- Plugin used-->
        <script>

            $(function () {
                var isAdmin = '@Convert.ToString(isAdmin)';
                $("#profileNav").on("click", function (event) {
                    event.stopPropagation();
                    if ($(".menu-dropdown").hasClass("d-none")) {
                        $(".menu-dropdown").removeClass("d-none");
                        $("#navArrowIcon").css({ "transform": "rotate(180deg)" });

                    } else {
                        $(".menu-dropdown").addClass("d-none");
                        $("#navArrowIcon").css({ "transform": "rotate(0deg)" });
                    }
                });

                $(document).on("click", function (event) {
                    if (!$(event.target).closest(".menu-dropdown").length) {
                        $(".menu-dropdown").addClass("d-none");
                        $("#navArrowIcon").css({ "transform": "rotate(0deg)" });
                    }
                });
            });
            function Logout() {
                localStorage.removeItem("cart");
                $.ajax({
                    url: '/User/Logout',
                    method: 'Get',
                    success: function (data) {
                        toastr.success(data, "Success");
                        window.location = "/";
                    },
                    error: function (xhr, status, error) {
                        toastr.error(error, "Error");
                    }
                });
            }

        </script>
    </div>
</body>
</html>